services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: app
    container_name: challenge-heroes
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - api

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: api
    container_name: challenge-heroes-api
    ports:
      - "3000:3000"
    volumes:
      - ../mock-api:/data
    restart: unless-stopped
